// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9f_wWRzOJ37la_gfXEkW-QfkYCJIOkI',
    appId: '1:404145146479:web:62a28e20de309bdc635b9a',
    messagingSenderId: '404145146479',
    projectId: 'chat-app-72932',
    authDomain: 'chat-app-72932.firebaseapp.com',
    storageBucket: 'chat-app-72932.firebasestorage.app',
    measurementId: 'G-6Q3HP5EGVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHguGuGyRlwEWQEsweWnxfhgiQBq1XXWc',
    appId: '1:404145146479:android:c997f61d30678901635b9a',
    messagingSenderId: '404145146479',
    projectId: 'chat-app-72932',
    storageBucket: 'chat-app-72932.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE9f_wWRzOJ37la_gfXEkW-QfkYCJIOkI',
    appId: '1:404145146479:web:94f793ac82bb85e7635b9a',
    messagingSenderId: '404145146479',
    projectId: 'chat-app-72932',
    authDomain: 'chat-app-72932.firebaseapp.com',
    storageBucket: 'chat-app-72932.firebasestorage.app',
    measurementId: 'G-ZJFQEBN3WM',
  );
}
